networks:
  - Polkadot Ecosystem Runtimes:
    - wss://polkadot-rpc-tn.dwellir.com
    - wss://statemint-rpc.dwellir.com
    - wss://polkadot-collectives-rpc.dwellir.com
    - wss://wss.api.moonbeam.network
    - wss://acala-polkadot.api.onfinality.io/public-ws
#    - wss://rpc-parachain.ajuna.network
    - wss://bifrost-polkadot.api.onfinality.io/public-ws
    - wss://mainnet.bitgreen.org
    - wss://rpc-para.clover.finance
    - wss://rpc.composable.finance
    - wss://spiritnet.kilt.io/
    - wss://fullnode.parachain.centrifuge.io
    - wss://parachain-rpc.darwinia.network
    - wss://rpc.astar.network
#    - wss://rpc.efinity.io
    - wss://node.pol.equilibrium.io/
    - wss://0.rpc.frequency.xyz
  #  - wss://c1.hashed.network
    - wss://rpc.hydradx.cloud
    - wss://polkadot.api.integritee.network
    - wss://api.interlay.io/parachain
#    - wss://k-ui.kapex.network
#    - wss://polkadot.kylin-node.co.uk
    - wss://rpc.litentry-parachain.litentry.io
    - wss://parachain-rpc.origin-trail.network
#    - wss://rpc.parallel.fi
    - wss://api.phala.network/ws
    - wss://eu-ws.unique.network/
  - Kusama Ecosystem Runtimes:
    - wss://kusama-rpc.dwellir.com
    - wss://statemine-rpc.dwellir.com
    - wss://fullnode.altair.centrifuge.io
    - wss://rpc-amplitude.pendulumchain.tech
    - wss://rpc-parachain.bajun.network
    - wss://rpc.basilisk.cloud
    - wss://bifrost-parachain.api.onfinality.io/public-ws
    - wss://pioneer-rpc-3.bit.country/wss
    - wss://calamari.systems
    - wss://rpc-shadow.crust.network/
    - wss://kusama.rpc.ipci.io
    - wss://crab-parachain-rpc.darwinia.network/
#    - wss://kusama.dorafactory.org
    - wss://kusama.imbuenetwork.com
    - wss://kusama.api.integritee.network
    - wss://kabocha.jelliedowl.net
    - wss://karura-rpc-0.aca-api.network
    - wss://khala-api.phala.network/ws
  #  - wss://rpc.kico.dico.io
    - wss://api-kusama.interlay.io/parachain
#    - wss://rpc.mainnet.listen.io
    - wss://rpc.litmus-parachain.litentry.io
#    - wss://prod-kusama-collator-01.mangatafinance.cloud
    - wss://wss.api.moonriver.moonbeam.network
    - wss://heiko-rpc.parallel.fi
    - wss://rpc.composablenodes.tech
#    - wss://kusama.kylin-node.co.uk
    - wss://eu-ws-quartz.unique.network
#    - wss://rio-kusama.riocorenetwork.com
    - wss://kusama.rpc.robonomics.network/
#    - wss://snow-rpc.icenetwork.io
    - wss://rpc.shiden.astar.network
    - wss://ws.parachain-collator-2.c2.sora2.soramitsu.co.jp
    - wss://turing-rpc.dwellir.com
    - wss://zeitgeist-rpc.dwellir.com
  - Standalone Runtimes:
#    - wss://odyssey.aresprotocol.io
    - wss://entrypoint-finney.opentensor.ai:443
    - wss://mainnet.chainx.org/ws
    - wss://rpc.darwinia.network
    - wss://crab-rpc.darwinia.network
#    - wss://edgeware-rpc1.jelliedowl.net
    - wss://rpc.joystream.org
    - wss://mainnet-rpc.polymesh.network
