site_name: PySubstrate metadata docs
site_url: https://polkascan.github.io/py-substrate-interface/
repo_url: https://github.com/polkascan/py-substrate-metadata-docs
nav:
    - Overview: index.md
    - Polkadot: polkadot.md
    - Statemint: statemint.md
    - Collectives: collectives.md
    - Moonbeam: moonbeam.md
    - Acala: acala.md
    - Centrifuge: centrifuge.md
    - Kilt: kilt-spiritnet.md
    - Astar: astar.md
    - Kusama: kusama.md
    - Statemine: statemine.md
    - Moonriver: moonriver.md
    - Karura: karura.md
    - Shiden: shiden.md

theme: readthedocs
