site_name: PySubstrate metadata docs
repo_url: https://github.com/polkascan/py-substrate-interface

nav:
    - Usage: index.md
    - Polkadot Ecosystem Runtimes:
      - Overview: polkadot-runtimes.md
      - Polkadot: polkadot.md
      - Statemint: statemint.md
      - Collectives: collectives.md
      - Moonbeam: moonbeam.md
      - Acala: acala.md
      - Ajuna Polkadot: ajuna.md
      - Astar: astar.md
      - Darwinia Parachain: darwinia-parachain.md
      - Bifrost Polkadot: bifrost_polkadot.md
      - Bitgreen: bitgreen-parachain.md
      - Centrifuge: centrifuge.md
      - Clover: clover-mainnet.md
      - Composable Finance: composable.md
      - Efinity: efinity.md
      - Equilibrium parachain: equilibrium-parachain.md
      - Frequency: frequency.md
      - Hashed Network: hashed.md
      - HydraDX: hydradx.md
      - Integritee Shell: integritee-parachain.md
      - Interlay: interlay-parachain.md
      - Kapex: totem-parachain.md
      - KILT Spiritnet: kilt-spiritnet.md
      - Kylin Network: kylin.md
      - Litentry: litentry-parachain.md
      - Nodle: nodle-para.md
      - OriginTrail Parachain: origintrail-parachain.md
      - Parallel: parallel.md
      - Phala: phala.md
      - UNIQUE: unique.md

    - Kusama Ecosystem Runtimes:
      - Overview: kusama-runtimes.md
      - Kusama: kusama.md
      - Statemine: statemine.md
      - Altair: altair.md
      - Amplitude: amplitude.md
      - Bajun Kusama: bajun.md
      - Basilisk: basilisk.md
      - Bifrost: bifrost.md
      - Dorafactory Network: dora-ksm-parachain.md
      - Calamari Parachain: calamari.md
      - Crust Shadow: crust-collator.md
      - Ipci: ipci.md
      - Crab Parachain: crab-parachain.md
      - imbue kusama: imbue.md
      - Integritee Network (Kusama): integritee-parachain.md
      - Kabocha: kabocha-parachain.md
      - Karura: karura.md
      - Khala: khala.md
      - KICO: kico.md
      - kintsugi: kintsugi-parachain.md
      - Listen Network: listen-parachain.md
      - Litmus: litmus-parachain.md
      - Mangata Kusama Mainnet: mangata-parachain.md
      - Moonriver: moonriver.md
      - Parallel Heiko: heiko.md
      - Picasso: picasso.md
      - Pichiu Network: pichiu.md
      - Pioneer Network: pioneer-runtime.md
      - QUARTZ by UNIQUE: quartz.md
      - Rio Kusama Mainnet: parachain-rio.md
      - Robonomics: robonomics.md
      - Snow Kusama: snow.md
      - Shiden: shiden.md
      - SORA Kusama: sora_ksm.md
      - SubsocialX: subsocial-parachain.md
      - Turing Network: turing.md
      - Zeitgeist: zeitgeist.md
    - Libary documentation: https://polkascan.github.io/py-substrate-interface/

theme:
  name: "material"
  logo: https://avatars.githubusercontent.com/u/43450475
  highlightjs: true
  hljs_languages:
    - python
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
#    - toc.integrate

plugins:
  - autorefs

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/polkascan/py-substrate-interface
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/polkascan

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences
